name       : rapidfuzz-cpp
version    : 1.10.2
release    : 1
source     :
    - https://github.com/maxbachmann/rapidfuzz-cpp/archive/refs/tags/v1.10.2.tar.gz : ec86c6ddbf7cec858f672f694909d33f8596e13e6fddb21438b54736dec2ef40
homepage   : https://github.com/maxbachmann/rapidfuzz-cpp
license    : MIT
component  : programming.devel
summary    : Rapid fuzzy string matching in C++ using the Levenshtein Distance
description: |
    RapidFuzz is a fast string matching library for Python and C++, which is using the string similarity calculations from FuzzyWuzzy
patterns  : /*
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
